local CU = require 'utils.configs-utils'

---@class PresetSplitSegment
---@field name string, the target that will trigger the autosplit `item`|`recipe`|`technology`|`entity`|`launch`?
---@field type string, the target action that will trigger autosplit
---@field time string, split time formatted as `hh:mm::ss`, with optional hh and mm
---@field icon? string, AUTOGENERATED FROM `type/name`
---@field ticks? number, AUTOGENERATED from `time`

---@class PresetModule
---@field name string
---@field type string, `mod`|`startup`|`runtime`

---@class Preset
---@field name string, ID of the preset
---@field localised_name LocalisedString
---@field time string, AUTOGENERATED from last PresetSplitSegment::time
---@field allow_manual_splits boolean
---@field splits PresetSplitSegment[], a.k.a. the livesplits
---@field modules PresetModule[], the required mod settings or mods for this run

return CU.parse_config_table({
    ['any%'] = {
        name = 'any%',
        localsed_name = {},
        splits = {
            { type = 'technology', name = 'automation-science-pack', time =    '5:00' },
            { type = 'technology', name = 'logistic-science-pack',   time =   '20:00' },
            { type = 'technology', name = 'chemical-science-pack',   time =   '40:00' },
            { type = 'technology', name = 'production-science-pack', time = '1:08:00' },
            { type = 'technology', name = 'utility-science-pack',    time = '1:12:00' },
            { type = 'technology', name = 'space-science-pack',      time = '1:23:00' },
        }
        time = '1:23:00',
        allow_manual_splits = false,
        modules = {}
    },
})
